/**
 * Gym Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HealthStatus { 
    status: string;
    application: string;
    version: string;
    timestamp: string;
}

