/**
 * ProjectName API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    readonly id?: number;
    username: string;
    email: string;
    readonly createdAt?: string;
    readonly updatedAt?: string;
}

