/**
 * ProjectName API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationError } from './validation-error';


export interface ValidationErrorResponse { 
    message: string;
    status: number;
    timestamp: string;
    errors: Array<ValidationError>;
}

