spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

logging:
  level:
    com.projectname: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.web.servlet.error: DEBUG
